### ISSUE TITLE
Re: Local_pw_expiration.sh

### ISSUE THREAD

**Issue by Genesis2kx** [ducksrfr/mac_admin#1]
Is there a way to programmatically click the "Change Password..." button in the System Preference Pane that opens up? I feel this one extra step would be golden to using this implementation.

**Comment by ducksrfr** [comment]
@Genesis2kx Good idea, check out the new version! It took some trial and error before I noticed that the characters following "Change Password" were `…` and not `...`

**Comment by Genesis2kx** [comment]
Sounds good i'll give it a run. Also, what's the `xmlString` variable used for? I couldn't find it being used in the script after it was declared.

**Comment by ducksrfr** [comment]
Ah, that looks like a variable I used in another script that I overlooked when copy and pasting. It's removed now.
